project_id = "formula-intima"

[functions.create-payment]
verify_jwt = true

[functions.mp-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false
